kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    application: httpd-test-image
  name: httpd-test-image
  annotations:
    description: 'httpd image for AJP test'

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: httpd-test-image-ex01-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'httpd-test-image-ex01:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'httpd-base-test-image-ex01:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/mn-1221/httpd_test_image-ex01.git'
    contextDir:
      
